### PR TITLE
Disabled non engagement based features.

### PR DESCRIPTION
**Pull request by dpatchigolla**
Also modified model path name to make it work as standalone project

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by DipanjanAtRudderLabs** [comment]
This looks fine to me. @dpatchigolla - not closing and merging yet since review by @bwalvoord is pending. @bwalvoord - you can close and merge once satisfied

**Comment by bwalvoord** [comment]
I would add these features back to the project as they are Top of Funnel metrics that most of our customers will have.  These are also standard UTM params that we manage within the context object.  

        - first_campaign_name
        - last_campaign_name
        - first_source_name
        - last_source_name
        - campaigns_list
        - mediums_list
        - sources_list
        - campaign_sources

**Comment by DipanjanAtRudderLabs** [comment]
@Benjamin Walvoord ***@***.***> - these will be in a separate
repo. That repo will be referenced for Profiles-ML projects only

**Review by bwalvoord — APPROVED** [review]
Looks good to me based on prior feedback w/ Dipanjan

**Pull request merged**
